services:
  mongo:
    image: mongo:4.4
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Akif
      - MONGO_INITDB_ROOT_PASSWORD=Akif0012
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  visiting-card:
    build: .
    container_name: visiting_card_service
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECT=mongodb+srv://Akif:Akif0012@cluster0.xy55o.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:
    # You can optionally specify a driver here if needed, but default is usually fine

networks:
  app-network:
    driver: bridge
